# settings for trx steelseries joystick

angular_axis: 2 # right side stick - right-left
angular_reverse: false
angular_clamp: 0
angular_multiplier: 1

linear_axis: 3 # right side stick - up-down
linear_reverse: false
linear_clamp: 0
linear_multiplier: 1

deadman_button: 6 # button L1 
twist_topic: mobile_base_controller/cmd_vel

